django/solarvault/control/urls.py
from django.urls import path

from . import views

app_name = "control"
urlpatterns = [
    path("", views.psu_control, name ="index")
]

django/solarvault/read_state/urls.py
from django.urls import path

from . import views

app_name = "read_state"
urlpatterns = [
    path("", views.read_data, name ="read_data")
]

django/solarvault/settings/urls.py
from django.urls import path

from . import views

app_name = "settings"
urlpatterns = [
    path("", views.index, name ="index")
]

django/solarvault/solarvault/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("settings.urls")),
    path('control/', include("control.urls")),
    path('read/', include("read_state.urls"))
]

django/solarvault/read_state/models.py
from django.db import models

# Create your models here.

django/solarvault/control/views.py
from django.conf import settings
from django.shortcuts import render
from hanmatek import HM3xxP

# Create your views here.
def psu_control(request):
    if len(request.GET) > 0:
        interface = request.GET['if']
        try:
            psu = HM3xxP(interface)
        except Exception:
            message = "Failed to initialise serial port. Choose another Serial Interface."
            return render(request, "control/control.html", {
                "message": message
            })
        else:
            # Check if voltage is a numerical value
            try:
                if 0 <= float(request.GET['v']) <= 32:
                    voltage = request.GET['v']
            except Exception:
                psu.write("output", False)
                message = "Voltage is not a numerical value or out of range."
                return render(request, "control/control.html", {
                    "message": message
                })
            # Check if current is a numerical value
            try:
                if 0 <= float(request.GET['c']) <= 5:
                    current = request.GET['c']
            except Exception:
                psu.write("output", False)
                message = "Current is not a numerical value."
                return render(request, "control/control.html", {
                    "message": message
                })
            # Check if output is a boolean value
            if request.GET['o'].lower() == "true" or request.GET['o'].lower() == "false":
                current = request.GET['o']
            else:
                psu.write("output", False)
                message = "Output is not a boolean value."
                return render(request, "control/control.html", {
                    "message": message
                })
            
            current = request.GET['c']
            output = request.GET['o'].capitalize()
            psu.write("voltage:set", voltage)
            psu.write("current:set", current)
            psu.write("output", output)
            return render(request, "control/control.html", {
                "interface": f"Interface: {interface}",
                "voltage": f"Voltage: {voltage} [V]",
                "current": f"Current: {current} [A]",
                "output": f"Output ON: {output}"
            })
    else:
        message = "No PSU defined. Go to settings or use settings paramters in URL."
        return render(request, "control/control.html", {
            "message": message
        })

django/solarvault/read_state/views.py
from django.shortcuts import render
from hanmatek import HM3xxP

# Create your views here.
def read_data(request):
    if len(request.GET) > 0:
        interface = request.GET['if']
        try:
            psu = HM3xxP(interface)
        except Exception:
            message = "Failed to initialise serial port. Choose another Serial Interface."
            return render(request, "control/control.html", {
                "message": message
            })
        else:
            return psu.read("power")

django/solarvault/settings/views.py
from django.shortcuts import render
import serial.tools
import serial.tools.list_ports


# Create your views here.
def index(request):
    serial_devices = serial.tools.list_ports.comports()
    
    return render(request, "settings/settings.html", {
        "devices": serial_devices
    })

django/solarvault/control/templates/control/control.html
{% extends "layout.html" %}

{% block  title%}
Control
{% endblock %}

{% block body %}
    <div class="container mt-5 text-primary">
        <div class="row">
            <div class="col-md-6">
                {% if message %}
                <div class="text-warning">{{ message }}</div>
                {% endif %}
                <div class="text-success">{{ interface }}</div>
                <div class="text-success">{{ voltage }}</div>    
                <div class="text-success">{{ current }}</div>
                <div class="text-success">{{ output }}</div>
            </div>
        </div>
{% endblock %}

django/solarvault/control/templates/control/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Settings</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>

django/solarvault/settings/templates/settings/settings.html
{% extends "layout.html" %}

{% block title %}
Settings
{% endblock %}

{% block body %}
<div class="container mt-5 text-primary">
    <h3>PSU Control Settings</h3>
    <form action="{% url 'control:index' %}" method="get">
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="if">Interface:</label>
                <select id="if" name="if" class="form-control">
                    {% for device in devices %}
                        <option value="{{ device.device }}">{{ device.device }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="v">Voltage:</label>
                <input type="number" id="v" name="v" class="form-control" required min="0" max="30" step="0.1">
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="c">Current:</label>
                <input type="number" id="c" name="c" class="form-control" required min="0" max="5" step="0.01">
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="o">Output:</label>
                <select name="o" id="o" class="form-control">
                    <option value="True">ON</option>
                    <option value="False">OFF</option>
                </select>
            </div>
        </div>

        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}